[package]
name = "rxml_validation"
version = "0.8.1"
authors = ["Jonas Sch√§fer <jonas@zombofant.net>"]
license = "MIT"
edition = "2018"
description = "Plumbing crate for rxml and rxml_proc crates."
repository = "https://github.com/horazont/rxml"
keywords = ["xml"]
readme = true

